POST http://{{host}}/event
    ?WorkerActivityName=Available
    &EventType=worker.activity.update
    &ResourceType=worker
    &WorkerTimeInPreviousActivityMs=59514
    &Timestamp=1609180489
    &WorkerActivitySid=WA001
    &WorkerPreviousActivitySid=WA002
    &WorkerTimeInPreviousActivity=59
    &AccountSid=AC001
    &WorkerName=Worker1
    &Sid=EV001
    &TimestampMs=1609180489150
    &WorkerSid=WK001
    &WorkspaceSid=WS001
    &WorkspaceName=TestEvents
    &WorkerPreviousActivityName=Offline
    &EventDescription=Worker%20Worker1%20updated%20to%20Available%20Activity
    &ResourceSid=WK001
    &WorkerAttributes=%7B%7D
